---
- hosts: "{{ TARGET_HOSTS | default('local') }}"  
  vars:
######################
#    KEY_PASS: 
######################
    
    user: "{{ USER | default('appusr') }}"
    product_name: "{{ PRODUCT_NAME }}"
    
    alias: wso2carbon
    keystore_filename: wso2carbon.jks
    truststore_filename: client-truststore.jks
    keystore: "{{ certs_path }}/{{ keystore_filename }}"    
    truststore: "{{ certs_path }}/{{ truststore_filename }}"
    
    keysize: 2048
    expires: 3650
    selfsigned_cert: "{{ certs_path }}/wso2carbon.cer"

    selfsignedcertificate:
        - { country: US,
            state: Illinois,
            locality: Chicago,
            organization_unit: Engineering,
            organization: Devry University,
            cname: "{{ ansible_hostname }}"
           }
  roles:
    - { role: certificate-n-keystores_create }

